// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/talmud-contents/LibraryEditorial.tsx": () => import("../components/mockups/talmud-contents/LibraryEditorial.tsx"),
  "./components/mockups/talmud-contents/SidebarNav.tsx": () => import("../components/mockups/talmud-contents/SidebarNav.tsx"),
  "./components/mockups/talmud-contents/StudyDashboard.tsx": () => import("../components/mockups/talmud-contents/StudyDashboard.tsx")
};
